channels:
  global:
    display_name: 'Global'
    format:
      - text: '&c[&6%channel%&c] '
        hover: '&6Click to switch to this channel!'
        click_type: 'SUGGEST_COMMAND'
        click_text: '/channel set %channel_id%'
      - text: '&c[&6%player_uuid%&c]'
        permission: 'incendochat.admin'
      - text: '%vault_prefix% %player_displayname%&7: '
        hover: '&6Click to message this player!'
        click_type: 'SUGGEST_COMMAND'
        click_text: '/msg %player_name% '
      - text: '&r%message%'
    permission: ''
    ping_format: '&c@%name%&r'
    priority: -1
messages:
  list-header: '&6&lIncendoChat&8> &7Channel List'
  list-header-active: '&eActive Channels (Click to leave):'
  list-header-available: '&eAvailable Channels (Click to join):'
  list-item: '&7- &6%channel%'
  list-item-current: '&7- &6%channel% (Current)'
  list-hover-join: '&6Click to join the channel'
  list-hover-leave: '&6Click to leave the channel'
  active-channel-set: '&6&lIncendoChat&8> &7Your active channel was set to: %channel%'
  channel-joined: '&6&lIncendoChat&8> &7You joined channel: %channel%'
  channel-left: '&6&lIncendoChat&8> &7You left channel: %channel%'
