channels:
  global:
    display_name: 'Global'
    format:
      - text: '&c[&6%channel%&c] '
        hover: '&6Click to join this channel!'
        click_type: 'SUGGEST_COMMAND'
        click_text: '/channel %channel_id%'
      - text: '&c[&6%player_uuid%&c]'
        permission: 'incendochat.admin'
      - text: '%vault_prefix% %player_displayname%&7: '
        hover: '&6Click to message this player!'
        click_type: 'SUGGEST_COMMAND'
        click_text: '/msg %player_name% '
      - text: '&r%message%'
    permission: ''
    ping_format: '&c@%name%&r'
    priority: -1
messages:
  help-header: '&6&lIncendoChat&8> &7Help'
  list-header: '&6&lIncendoChat&8> &7Channel List'
  list-header-active: '&eActive Channels:'
  list-header-available: '&eAvailable Channels:'
  list-item: '&7- &6%channel%'
  list-hover-join: '&6Click to join the channel'
  list-hover-leave: '&6Click to leave the channel'
