name: IncendoChat
version: ${project.version}
main: com.github.sauilitired.incendochat.IncendoChat
api-version: 1.13
depend: [PlaceholderAPI]
softdepend: []
authors: [Citymonstret]
permissions:
  incendochat.admin:
    default: op
  incendochat.channel:
    default: op
  incendochat.channel.join:
    default: op
  incendochat.channel.leave:
    default: op
  incendochat.channel.list:
    default: op
  incendochat.channel.set:
    default: op
  incendochat.channel.send:
    default: op
