name: IncendoChat
version: ${project.version}
main: com.github.sauilitired.incendochat.IncendoChat
api-version: 1.13
depend: [PlaceholderAPI, Vault]
softdepend: []
authors: [Citymonstret]
permissions:
  incendochat.admin:
    default: op
